Add contribution blocking level
guardian/tags-thrift-schema pull request #26
Opened 2019-05-09 08:39 UTC by itsibitzi

Rename `AdBlockingLevel` to `BlockingLevel` and add contribution ask blocking.

2019-06-14 10:32 UTC, akash1810 reviewed
Can we freely rename fields in thrift, or do we need some sort of migration?

2019-06-14 10:48 UTC, itsibitzi commented
My understanding is the thrift would still serialize anyway since it's based on slots, but might be wrong there. That being said we never used the previous version!

2019-06-14 10:55 UTC, sihil requested changes
Couple of things to clarify.

2019-06-14 10:55 UTC, sihil commented on src/main/thrift/tag.thrift
> +    /** Ad blocking level used to block ads when a tag is applied to content */
Comment is identical to that on the field above.

2019-06-14 10:55 UTC, sihil commented on version.sbt
> +version in ThisBuild := "2.6.0"
Typically this is bumped automatically by the release plugin and should not be touched in a PR.

2019-06-14 10:56 UTC, sihil commented
The field hasn't been renamed - only the name of the enum. I'm not sure if that's a breaking change but understand why it's been made.

2019-07-22 13:23 UTC, itsibitzi commented
Fixed the comments - is it ok to merge this? I'd prefer to roll this out ahead of the tag manager and flexible content changes

2019-08-12 10:49 UTC, sihil commented
Sorry for missing this @itsibitzi. Was about to ask for further clarification as to why the version was being bumped in a PR. Just looked and saw this isn't using the release plugin which (for me) violates principle of least surprise.

2019-08-12 10:49 UTC, sihil approved these changes

2019-08-12 10:52 UTC, sihil commented
Sorry for missing this @itsibitzi. Was about to ask for further clarification as to why the version was being bumped in a PR. Just looked and saw this isn't using the release plugin which (for me) violates principle of least surprise.

2019-08-27 13:24 UTC, merged